{ pkgs, lib }:

let
  ruby = pkgs.ruby_3_3;
  
  # Use bundlerEnv to create a deterministic gem environment from gemset.nix
  # The gemset.nix is generated by running: nix run nixpkgs#bundix -- -l
  gems = pkgs.bundlerEnv {
    name = "smoke-tests-gems";
    inherit ruby;
    gemdir = ../services/smoke-tests;
    # gemset.nix, Gemfile, and Gemfile.lock are automatically picked up from gemdir
  };
in
pkgs.stdenv.mkDerivation {
  pname = "smoke-tests";
  version = "0.1.0";
  src = ../services/smoke-tests;
  
  buildInputs = [ ruby gems ];
  
  installPhase = ''
    mkdir -p $out/bin $out/share/smoke-tests
    cp -r . $out/share/smoke-tests/
    
    # Create wrapper that uses the pre-installed gems
    cat > $out/bin/smoke-tests <<EOF
#!${pkgs.bash}/bin/bash
export GEM_HOME="${gems}"
export GEM_PATH="${gems}:${gems}/lib/ruby/gems/${ruby.version.libDir}"
export PATH="${gems}/bin:${ruby}/bin:\$PATH"
cd $out/share/smoke-tests
exec bundle exec ruby app.rb "\$@"
EOF
    chmod +x $out/bin/smoke-tests
    
    # Create cucumber runner wrapper
    cat > $out/bin/smoke-tests-cucumber <<EOF
#!${pkgs.bash}/bin/bash
export GEM_HOME="${gems}"
export GEM_PATH="${gems}:${gems}/lib/ruby/gems/${ruby.version.libDir}"
export PATH="${gems}/bin:${ruby}/bin:\$PATH"
cd $out/share/smoke-tests
exec bundle exec cucumber "\$@"
EOF
    chmod +x $out/bin/smoke-tests-cucumber
  '';
  
  meta = with lib; {
    description = "TransferX Smoke Tests Service";
    license = licenses.mit;
  };
}
