{ pkgs, lib }:

let
  # Import shared SBOM traceability utilities
  traceability = import ../lib/sbom/nix-traceability.nix;

  ruby = pkgs.ruby_3_3;
  
  # Deterministic Ruby builds using bundlerEnv + bundix
  # ===================================================
  # 
  # bundlerEnv reads three files from gemdir:
  #   - Gemfile       (dependency declarations)
  #   - Gemfile.lock  (resolved versions)
  #   - gemset.nix    (SHA256 hashes for each gem)
  #
  # The gemset.nix file is generated by bundix and contains pinned hashes
  # for every gem, ensuring fully reproducible builds.
  #
  # To update gems:
  #   cd services/smoke-tests
  #   bundle lock --update           # Update Gemfile.lock
  #   nix run nixpkgs#bundix -- -l   # Regenerate gemset.nix
  #   mv gemset.nix ../release/smoke-tests-gemset.nix
  #   git add Gemfile.lock release/smoke-tests-gemset.nix
  #
  # To add a new gem:
  #   1. Add to Gemfile
  #   2. Run: bundle lock
  #   3. Run: nix run nixpkgs#bundix -- -l
  #   4. mv gemset.nix ../release/smoke-tests-gemset.nix
  #   5. Commit: Gemfile, Gemfile.lock, release/smoke-tests-gemset.nix
  #
  # Create a gemdir that includes the gemset.nix from release/
  gemdir = pkgs.runCommand "smoke-tests-gemdir" {} ''
    mkdir -p $out
    cp -r ${../services/smoke-tests}/* $out/
    cp ${./smoke-tests-gemset.nix} $out/gemset.nix
  '';
  
  gems = pkgs.bundlerEnv {
    name = "smoke-tests-gems";
    inherit ruby;
    gemdir = gemdir;
  };

  # Extract gem info using shared traceability library
  # For gems, we pass the gem name as an override since bundlerEnv uses attribute names
  extractGemInfo = name: gem:
    traceability.extractPackageInfo { nameOverride = name; } gem;

  # Get all gem names
  gemNames = builtins.attrNames gems.gems;
  
in
pkgs.stdenv.mkDerivation {
  pname = "smoke-tests";
  version = "0.1.0";
  src = ../services/smoke-tests;
  
  buildInputs = [ ruby gems ];
  
  installPhase = ''
    mkdir -p $out/bin $out/share/smoke-tests
    cp -r . $out/share/smoke-tests/
    
    # Create wrapper that uses the pre-installed gems
    cat > $out/bin/smoke-tests <<EOF
#!${pkgs.bash}/bin/bash
export GEM_HOME="${gems}"
export GEM_PATH="${gems}:${gems}/lib/ruby/gems/${ruby.version.libDir}"
export PATH="${gems}/bin:${ruby}/bin:\$PATH"
cd $out/share/smoke-tests
exec bundle exec ruby app.rb "\$@"
EOF
    chmod +x $out/bin/smoke-tests
    
    # Create cucumber runner wrapper
    cat > $out/bin/smoke-tests-cucumber <<EOF
#!${pkgs.bash}/bin/bash
export GEM_HOME="${gems}"
export GEM_PATH="${gems}:${gems}/lib/ruby/gems/${ruby.version.libDir}"
export PATH="${gems}/bin:${ruby}/bin:\$PATH"
cd $out/share/smoke-tests
exec bundle exec cucumber "\$@"
EOF
    chmod +x $out/bin/smoke-tests-cucumber
  '';
  
  # Expose gem dependencies for SBOM traceability
  passthru = {
    inherit ruby;
    gemEnv = gems;
    
    sbomDependencies = {
      # All gems are runtime dependencies for smoke-tests
      runtime = builtins.map (name: extractGemInfo name gems.gems.${name}) gemNames;
      dev-only = [];  # No dev-only gems for smoke-tests
      all = builtins.map (name: extractGemInfo name gems.gems.${name}) gemNames;
    };
  };
  
  meta = with lib; {
    description = "TransferX Smoke Tests Service";
    license = licenses.mit;
  };
}
